// source code/personal-heath-view/src/pages/user/NewsDetail.jsx
import { useEffect, useState } from 'react';
import { Button, Col, Rate, Row, Space, Typography, message } from 'antd';
import { useNavigate } from 'react-router-dom';
import client from '@/api/client.js';
import { timeAgo } from '@/utils/time.js';
import NewsCard from '@/components/NewsCard.jsx';
import Comments from '@/components/Comments.jsx';

const NewsDetail = () => {
  const navigate = useNavigate();
  const [news, setNews] = useState(() => {
    const cache = sessionStorage.getItem('newsInfo');
    return cache ? JSON.parse(cache) : null;
  });
  const [saveFlag, setSaveFlag] = useState(false);
  const [topList, setTopList] = useState([]);
  const [score, setScore] = useState(0);
  const [existingScore, setExistingScore] = useState(null);

  useEffect(() => {
    if (!news) {
      navigate('/user/news-record');
      return;
    }
    loadSaveStatus(news.id);
    loadRecommend();
    loadScore(news.id);
  }, [news]);

  const loadSaveStatus = async id => {
    const { data } = await client.post('/news-save/queryUser', { newsId: id });
    if (data.code === 200) {
      setSaveFlag(data.data.length !== 0);
    }
  };

  const loadRecommend = async () => {
    const { data } = await client.get('/news/queryRecommend/3');
    if (data.code === 200) {
      setTopList(data.data);
    }
  };

  const loadScore = async id => {
    const { data } = await client.post('/score/query', { articleId: id });
    if (data.code === 200 && data.data.length) {
      setExistingScore(data.data[0].total);
    } else {
      setExistingScore(null);
    }
  };

  const handleToggleSave = async () => {
    const { data } = await client.post('/news-save/operation', { newsId: news.id });
    if (data.code === 200) {
      setSaveFlag(prev => !prev);
      message.success(!saveFlag ? 'collect success' : 'cancel collect success');
    }
  };

  const handleScore = async value => {
    setScore(value);
    const payload = { total: value, articleId: news.id };
    const { data } = await client.post('/score/save', payload);
    if (data.code === 200) {
      message.success('score success');
      loadScore(news.id);
    }
  };

  const handleNewsClick = item => {
    sessionStorage.setItem('newsInfo', JSON.stringify(item));
    setNews(item);
  };

  if (!news) {
    return null;
  }

  return (
    <Row gutter={32}>
      <Col xs={24} lg={18}>
        <div>
          <Typography.Title level={1}>{news.name}</Typography.Title>
          <Space style={{ fontSize: 14, marginBottom: 16 }}>
            <span className="news-tags">{news.tagName}</span>
            <span>{timeAgo(news.createTime)}</span>
            <Button size="small" onClick={handleToggleSave}>
              {saveFlag ? 'cancel collect' : 'collect'}
            </Button>
          </Space>
          <div dangerouslySetInnerHTML={{ __html: news.content }} />
        </div>
        <Comments contentId={Number(news.id)} contentType="NEWS" />
      </Col>
      <Col xs={24} lg={6}>
        <div style={{ marginBottom: 24 }}>
          <Typography.Title level={4}>{existingScore ? 'my score' : 'score now'}</Typography.Title>
          {existingScore ? (
            <Rate disabled value={existingScore} allowHalf />
          ) : (
            <Rate value={score} onChange={handleScore} allowHalf />
          )}
        </div>
        <Typography.Title level={4}>news recommendation</Typography.Title>
        {topList.map(item => (
          <div key={item.id} style={{ marginBottom: 16 }}>
            <NewsCard news={item} onClick={handleNewsClick} />
          </div>
        ))}
      </Col>
    </Row>
  );
};

export default NewsDetail;

// source code/personal-heath-view/src/views/user/NewsDetail.vue
<template>
    <el-row>
        <el-col :span="18">
            <div style="padding-right: 50px;box-sizing: border-box;">
                <div>
                    <h1>{{ newsInfo.name }}</h1>
                    <div
                        style="font-size: 12px;background-color: rgb(250, 250, 250);padding: 16px 6px;border-radius: 5px;">
                        <span class="news-tags">{{ newsInfo.tagName }}</span>
                        <span style="margin-left: 10px;">{{ parseTime(newsInfo.createTime) }}</span>
                        <el-button style="margin-left: 20px;" @click="saveNewsOperation" class="customer" size="mini">{{
                            !saveFlag ?
                                'collect' : 'cancel collect' }}</el-button>
                    </div>
                    <div v-html="newsInfo.content"></div>
                </div>
                <div>
                    <Evaluations :contentId="newsInfo.id" contentType="NEWS" />
                </div>
            </div>
        </el-col>
        <el-col :span="6">
            <div v-if="scoreList.length === 0">
                <h3 style="padding: 10px 30px;">score now</h3>
                <div style="background-color: rgb(248,249,250);margin-inline: 30px;padding: 20px;border-radius: 4px;">
                    <el-rate style="margin-left: 25px;" v-model="score" @change="scoreChange"></el-rate>
                </div>
            </div>
            <div v-else>
                <h3 style="padding: 10px 30px;">my score</h3>
                <div style="background-color: rgb(248,249,250);margin-inline: 30px;padding: 20px;border-radius: 4px;">
                    <el-rate style="margin-left: 25px;" v-model="scoreList[0].total" disabled show-score
                        text-color="#ff9900" score-template="{value}">
                    </el-rate>
                </div>

            </div>
            <h3 style="padding: 10px 30px;">news recommendation</h3>
            <el-col @click.native="newsItemClick(news)" :span="24" :key="index" v-for="(news, index) in newsTopList">
                <div style="padding: 8px 30px;box-sizing: border-box;">
                    <img :src="news.cover" :alt="news.name" style="width: 100%;height: 148px;border-radius: 5px;">
                    <div class="news-title">{{ news.name }}</div>
                    <div style="font-size: 12px;">
                        <span class="news-tags">{{ news.tagName }}</span>
                        <span style="margin-left: 10px;">{{ parseTime(news.createTime) }}</span>
                    </div>
                </div>
            </el-col>
        </el-col>
    </el-row>
</template>
<script>
import { timeAgo } from "@/utils/data"
import Evaluations from "@/components/Evaluations.vue";
export default {
    components: { Evaluations },
    name: "NewsDetail",
    data() {
        return {
            newsInfo: {},
            newsTopList: [],
            saveFlag: false,
            newsSaveList: [],
            scoreList: [],
            score: 0,
        }
    },
    created() {
        // 第一件事：是不是拿到存起来的资讯数据？
        this.getStorageInfo();
        this.loadAllTopNews();
        this.loadScore();
    },
    methods: {
        scoreChange() {
            const dto = {
                total: this.score,
                articleId: this.newsInfo.id
            }
            this.$axios.post('/score/save', dto).then(response => {
                const { data } = response;
                if (data.code === 200) {
                    this.$notify({
                        duration: 1000,
                        title: 'score',
                        message: 'score success',
                        type: 'success'
                    });
                    this.loadScore();
                }
            })
        },
        loadScore() {
            const dto = { articleId: this.newsInfo.id };
            this.$axios.post('/score/query', dto).then(response => {
                const { data } = response;
                if (data.code === 200) {
                    this.scoreList = data.data;
                }
            })
        },
        loadSaveStatus() {
            const newsSaveQueryDto = {
                newsId: this.newsInfo.id
            }
            console.log("查询的参数：" + JSON.stringify(newsSaveQueryDto));
            this.$axios.post('/news-save/queryUser', newsSaveQueryDto).then(response => {
                const { data } = response;
                if (data.code === 200) {
                    this.saveFlag = data.data.length !== 0;
                }
            })
        },
        // 收藏或取消收藏操作
        saveNewsOperation() {
            this.$axios.post('/news-save/operation', { newsId: this.newsInfo.id }).then(response => {
                const { data } = response;
                if (data.code === 200) {
                    this.$message.success(!this.saveFlag ? 'collect success' : 'cancel collect success');
                    this.saveFlag = !this.saveFlag;
                }
            })
        },
        newsItemClick(news) {
            this.newsInfo = news;
            this.loadSaveStatus();
        },
        // 转换时间
        parseTime(time) {
            return timeAgo(time);
        },
        getStorageInfo() {
            const newInfo = sessionStorage.getItem('newsInfo');
            this.newsInfo = JSON.parse(newInfo);
            this.loadSaveStatus();
        },
        // 查询推荐资讯
        loadAllTopNews() {
            this.$axios.get(`/news/queryRecommend/${3}`).then(response => {
                const { data } = response;
                if (data.code === 200) {
                    this.newsTopList = data.data;
                }
            })
        },
    }
};
</script>

<style scoped lang="scss">
.news-tags {
    display: inline-block;
    padding: 4px 10px;
    background-color: rgb(226, 242, 249);
    color: #1d3cc4;
    border-radius: 3px;
}
.news-title{
    margin-block: 10px;
    font-weight: 600;
}
</style>
